server:
  port: 9999
  servlet:
    context-path: /
logging:
  level:
    root: INFO
spring:
  application:
    name: music-player
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/music_bucket
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis
  mail:
    host: smtp.yandex.ru
    port: 465
    username: playervoker@yandex.ru
    password: 
    protocol: smtps
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger.html